// ──────────────────────────────────────────────
// Chat & Message Types
// ──────────────────────────────────────────────

/** The three primary chat modes the engine supports. */
export type ChatMode = "conversation" | "roleplay" | "visual_novel";

/** Role of a message in the conversation. */
export type MessageRole = "user" | "assistant" | "system" | "narrator";

/** A single chat conversation. */
export interface Chat {
  id: string;
  name: string;
  mode: ChatMode;
  characterIds: string[];
  personaId: string | null;
  promptPresetId: string | null;
  connectionId: string | null;
  createdAt: string;
  updatedAt: string;
  metadata: ChatMetadata;
}

/** Extra metadata stored on a chat. */
export interface ChatMetadata {
  /** Summary text for context injection */
  summary: string | null;
  /** Custom tags for organisation */
  tags: string[];
  /** Whether agents are enabled for this chat */
  agentsEnabled: boolean;
  /** Per-agent enable overrides (agentId → boolean) */
  agentOverrides: Record<string, boolean>;
  /** Any extra key-value data */
  [key: string]: unknown;
}

/** A single message within a chat. */
export interface Message {
  id: string;
  chatId: string;
  role: MessageRole;
  /** Which character sent this (null for user messages / narration) */
  characterId: string | null;
  content: string;
  /** Index into the swipes array for the currently displayed alternative */
  activeSwipeIndex: number;
  createdAt: string;
  /** Extra display data */
  extra: MessageExtra;
}

/** Additional data attached to a message. */
export interface MessageExtra {
  /** Display-formatted text (may differ from raw content) */
  displayText: string | null;
  /** Whether this message was generated by the AI vs typed by user */
  isGenerated: boolean;
  /** Token count of this message */
  tokenCount: number | null;
  /** Generation metadata */
  generationInfo: GenerationInfo | null;
}

/** Metadata about how a message was generated. */
export interface GenerationInfo {
  model: string;
  provider: string;
  temperature: number | null;
  tokensPrompt: number | null;
  tokensCompletion: number | null;
  durationMs: number | null;
  finishReason: string | null;
}

/** A swipe (alternate response) for a message. */
export interface MessageSwipe {
  id: string;
  messageId: string;
  index: number;
  content: string;
  createdAt: string;
  extra: MessageExtra;
}

/** Payload sent to start a generation. */
export interface GenerateRequest {
  chatId: string;
  userMessage: string | null;
  /** If set, regenerate the message at this ID */
  regenerateMessageId: string | null;
  /** Override connection for this generation */
  connectionId: string | null;
}

/** An SSE event from the generation stream. */
export interface StreamEvent {
  type: "token" | "agent_update" | "game_state" | "done" | "error";
  data: string;
  agentId?: string;
  messageId?: string;
}
